In [1]:
import numpy as np 
import pandas as pd

data = pd.read_csv("sales_data_sample.csv",encoding="latin1")

arr = data.to_numpy()

In [ ]:
print("Datatype: ", arr.dtype)

print("SHAPE:",arr.shape)
print("ROWS:",arr.shape[0])
print("COLUMNS:",arr.shape[1])

print("First Five Rows:\n",arr[0:5])
print("Last Five Rows:\n",arr[-5:])
print("First Five columns:\n", arr[:, 0:5])

In [ ]:
print("10th ROW: \n", arr[9])
print("10th Column: \n", arr[:,9])

In [ ]:
print("Qunatity+sales :\n", arr[:, [1,4]])

quan_ord = arr[:,1].astype(float)
print(arr[quan_ord > 50])
sales_ord = arr[:,4].astype(float)
print(arr[sales_ord>10000])

In [ ]:
condition = (quan_ord > 30) & (sales_ord > 5000)
print(arr[condition])

In [ ]:
# Task 11

# Calculate the:
# Total sales
# Average sales
# Minimum sales
# Maximum sales

print("Total Sales: ", np.sum(sales_ord))
print("Average Sales: ", np.mean(sales_ord))
print("Minimum Sales: ", np.min(sales_ord))
print("Maximum Sales: ", np.max(sales_ord))


In [ ]:
# Task 12

# Calculate the:

# Total quantity ordered
# Average quantity ordered
# Minimum quantity
# Maximum quantity

print("Total Quantity Order: ", np.sum(quan_ord))
print("Average Quantity Order: ", np.mean(quan_ord))
print("Minimum Quantity Order: ", np.min(quan_ord))
print("Maximum Quantity Order: ", np.max(quan_ord))

In [ ]:
# Task 13

# Find the standard deviation of Sales.

print("STD: ", np.std(sales_ord))

# Task 14

# Find the median Sales.
print("Median: ", np.median(sales_ord))
# Task 15

# Calculate:
# Total Revenue = sum of all Sales
# Then verify it using another NumPy approach.

total_revenue = np.sum(sales_ord)
print("Total Revenue : ", total_revenue)

sum_of_all_sales = np.mean(sales_ord) * np.size(sales_ord)
print("sum of all sales = :", sum_of_all_sales)


In [ ]:
# Task 16
# Count how many orders have:
# SALES > 5000

print("SALES > 5000:", len(arr[sales_ord > 5000]))
print("Sales > 5000: ", np.sum(sales_ord > 5000))

# Task 17
# Count how many orders have:
# QUANTITYORDERED > 40

print("QUANTITY ORDERED > 40 : ", len(arr[quan_ord > 40]))
print("Quantity ordered > 5000: ", np.sum(quan_ord > 40))

# Task 18
# Find how many orders satisfy:
# SALES > 5000 AND QUANTITYORDERED > 40

condition = (sales_ord > 5000) & (quan_ord > 40)
print("SALES > 5000 AND QUANTITYORDERED > 40: ", len(arr[condition]))
print("SALES > 5000 AND QUANTITYORDERED > 40: ", np.sum(condition))

 

In [ ]:
# Task 19
# Find the percentage of orders where:
# SALES > 5000

order_sales = arr[:, 4].astype(float)
order_sales_5000 = order_sales[order_sales > 5000]
percentage = (np.sum(order_sales > 5000) * 100) / np.size(order_sales)
print("Percentage of orders where sales > 5000: ", percentage)

In [19]:
# 🔴 Level 5 — Challenge
# Try these without looking up the solution.
# Task 20
# Find the row containing the highest Sales.
# Then extract the complete row.

sales_ord = arr[:, 4].astype(float)
row_highest_sale = np.argmax(sales_ord)
print("Row containing highest sales : ", row_highest_sale)
print("Complete Row containing highest sales : ", arr[row_highest_sale])


# Task 21
# Find the row containing the lowest Sales.
row_lowest_sale = np.argmin(sales_ord)
print("Row containing lowest sales : ", row_lowest_sale)
print("Complete Row containing lowest sales : ", arr[row_lowest_sale])

# Task 22
# Find the index/position of the order with the highest Sales.
print("Index containing highest sales : ", row_highest_sale)

# Task 23
# Find the top 10 highest sales values using NumPy.
sort_sales = np.sort(sales_ord)
print("top 10 highest sales :", sort_sales[-10:])

# Task 24
# Calculate the difference between:
# Maximum Sales − Minimum Sales
diff = np.max(sales_ord) - np.min(sales_ord)
print("Maximum Sales − Minimum Sales:", diff)



Row containing highest sales :  598
Complete Row containing highest sales :  [10407 76 100.0 2 14082.8 '4/22/2005 0:00' 'On Hold' 2 4 2005
 'Vintage Cars' 170 'S18_1749' 'The Sharp Gifts Warehouse' '4085553659'
 '3086 Ingle Ln.' nan 'San Jose' 'CA' '94217' 'USA' nan 'Frick' 'Sue'
 'Large']
Row containing lowest sales :  2249
Complete Row containing lowest sales :  [10425 11 43.83 6 482.13 '5/31/2005 0:00' 'In Process' 2 5 2005
 'Trucks and Buses' 54 'S32_2509' 'La Rochelle Gifts' '40.67.8555'
 '67, rue des Cinquante Otages' nan 'Nantes' nan '44000' 'France' 'EMEA'
 'Labrune' 'Janine' 'Small']
Index containing highest sales :  598
top 10 highest sales : [10993.5 11279.2 11336.7 11623.7 11739.7 11886.6 11887.8 12001.  12536.5
 14082.8]
Maximum Sales − Minimum Sales: 13600.67


In [21]:
data.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium


In [73]:
# Task 25 ⭐
# Create a new NumPy array containing:
# QUANTITYORDERED | PRICEEACH | SALES
# Then calculate the correlation between:
# Quantity Ordered and Sales
# Price Each and Sales
quan_arr = arr[:,1].astype(float)
priceeach_arr = arr[:,2].astype(float)
sales_arr = arr[:,4].astype(float)

# new_arr = np.concatenate((quan_arr, priceeach_arr, sales_arr), axis=1) # Not working

new_arr = np.column_stack((quan_arr, priceeach_arr, sales_arr))

correlation1 = np.corrcoef(quan_arr, sales_arr)
correlation2 = np.corrcoef(priceeach_arr, sales_arr)
print(new_arr)
print("Correlation between Quantity Ordered and Sales:", correlation1)
print("Correlation between Quantity Ordered and Sales:", correlation1[0,1])
print("Correlation between price each and Sales:", correlation2)
print("Correlation between price each and Sales:", correlation2[0,1])

[[  30.     95.7  2871.  ]
 [  34.     81.35 2765.9 ]
 [  41.     94.74 3884.34]
 ...
 [  43.    100.   5417.57]
 [  34.     62.24 2116.16]
 [  47.     65.52 3079.44]]
Correlation between Quantity Ordered and Sales: [[1.         0.55142619]
 [0.55142619 1.        ]]
Correlation between Quantity Ordered and Sales: 0.5514261919183572
Correlation between price each and Sales: [[1.         0.65784093]
 [0.65784093 1.        ]]
Correlation between price each and Sales: 0.6578409283176873


In [71]:
idx = [1,2,4]
new_arr = arr[:,idx].astype(float)
new_arr

array([[  30.  ,   95.7 , 2871.  ],
       [  34.  ,   81.35, 2765.9 ],
       [  41.  ,   94.74, 3884.34],
       ...,
       [  43.  ,  100.  , 5417.57],
       [  34.  ,   62.24, 2116.16],
       [  47.  ,   65.52, 3079.44]], shape=(2823, 3))

In [78]:
np.isnan(sales_arr)

array([False, False, False, ..., False, False, False], shape=(2823,))